const IMAGES = {
    // Logo 
    catModalHomePage: '/images/catModalHomePageNew.png',
    bgDownBt:'/images/bg-downBt.png',
    downBt:'/images/downBt.png',
    crop:'/images/crop.png',
    group:'/images/Group.png',
    footerGreen:'/images/footerGreen.png',
    footerOrange:'/images/footerOrange.png',
    Howto:'/images/Howto.png',
    buttonDown:'/images/buttonDown.png',
    buttonUp:'/images/buttonUp.png',
    user: '/images/user.png',
    defaultImg: '/images/defaultImg.png',
    map: '/images/map.png',
    imageLogo: '/images/imageLogo.png',
    step1desc:'/images/onefor5step.png',
    step2desc:'/images/twofor5step.png',
    step3desc:'/images/threefor5step.png',
    step4desc:'/images/fourfor5step.png',
    step5desc:'/images/fivefor5step.png',
    step1:'/images/step1.png',
    step2:'/images/step2.png',
    step3:'/images/step3.png',
    step4:'/images/step4.png',
    step5:'/images/step5.png',
    deviceRightfor4step:'/images/deviceRightfor4step.png',
    deviceLeftfor4step:'/images/deviceLeftfor4step.png',
    scrollDown:'/images/NewScrollDown.png',
    bgAccountHeader:'/images/bgAccountHeader.png',
    greenBg: '/images/greenBg.png',
    accountLink: '/images/accountLink.png',
    whyUse1: '/images/whyUse1.png',
    whyUse2: '/images/whyUse2.png',
    userThumbnailEdit: '/images/pencil.png'
};
export default IMAGES;